//Add text for testing 

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from persim import plot_diagrams
from ripser import ripser, lower_star_img
import numpy as np
from numpy import genfromtxt
from scipy.spatial import distance_matrix
import copy
import string

In [2]:
alphabet = list(string.ascii_lowercase)
extra = ['.', ',','space', '-', ':', ';']
alphabet_full = alphabet + extra

In [3]:
df = pd.read_csv('letters.csv', header=None, index_col=0)
df

1    2    3    4    5    6    7    8    9    10   ...  91   92   93   94   \
0                                                     ...                       
1     0    0    0    0    1    1    0    0    0    0  ...    0    0    0    0   
2     0    0    1    1    1    1    0    0    0    0  ...    0    0    0    0   
3     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
6     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
7     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
8     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
9     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
11    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
13    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
14    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
15    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
16    0    0    0    0    0    0    0    0    0    0  ...    0    0    1    0   
17    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
18    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
19    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
20    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
21    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
22    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
23    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
24    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
25    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
26    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
27    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
28    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
29    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
30    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
31    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
32    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    95   96   97   98   99   100  
0                                 
1     0    0    0    0    0    0  
2     0    0    0    0    0    0  
3     0    0    0    0    0    0  
4     0    0    0    0    0    0  
5     0    0    0    0    0    0  
6     0    0    0    0    0    0  
7     0    0    0    0    0    0  
8     0    0    0    0    0    0  
9     0    0    0    0    0    0  
10    0    0    0    0    0    0  
11    0    0    0    0    0    0  
12    0    0    0    0    0    0  
13    0    0    0    0    0    0  
14    0    0    0    0    0    0  
15    0    0    0    0    0    0  
16    0    0    0    0    0    0  
17    0    0    0    0    0    0  
18    0    0    0    0    0    0  
19    0    0    0    0    0    0  
20    0    0    0    0    0    0  
21    0    0    0    0    0    0  
22    0    0    0    0    0    0  
23    0    0    0    0    0    0  
24    0    0    0    0    0    0  
25    1    0    0    0    0    0  
26    0    0    0    0    0    0  
27    0    0    0    0    0    0  
28    1    0    0    0    0    0  
29    0    0    0    0    0    0  
30    0    0    0    0    0    0  
31    0    0    0    0    0    0  
32    0    0    0    0    0    0  

[32 rows x 100 columns]

In [4]:
'''
Todo:
Get this down to only one loop
Fix rerun
'''

#list of each Scanning technique, empty lists
# for index_df in enumerate(data_chunk):
#      
#     data_chunk= [df_l_R,df_u_d,df_SUL,df_PUL,df_PLR]
    
df_list_up_down, df_list_left_right, df_list_SUL, df_list_PUL, df_list_PLR,\
df_list_RL, df_list_DU, df_list_CEN, df_list_SLL = ([] for i in range(9))

#iiterate through each row that represents part of the Latin Alphabet
for index, row in df.iterrows():
    #Chunks turns the row of 100 to 10 lists of 10 elments
    chunks = [list(row)[x:x+10] for x in range(0, len(list(row)), 10)]
    #print(chunks)
    #Creates empty list for each scanning technique to append the chunks
    chunks_up_down, chunks_left_right, chunks_SUL, chunks_PUL, chunks_PLR,\
    chunks_RL, chunks_DU, chunks_CEN, chunks_SLL = ([] for i in range(9))

    #loop through cunck of 1s and 0s I think could be turned into list comprehension
    for c_index, c_list in enumerate(chunks):
        #Creates empty list for each row
        u_list_up_down, u_list_left_right, u_list_SUL, u_list_PUL, u_list_PLR,\
        u_list_RL, u_list_DU, u_list_CEN, u_list_SLL = ([] for i in range(9))

        #List comprehension for creating the scanned numbers in each row
        #Scanning left to right 1s become the number column they are in
        u_list_left_right = [100 if item==0 else item*(idx+1) for idx, item in enumerate(c_list)]
        #Scanning Right to Left
        u_list_RL = [100 if item==0 else 10-item*(idx+1) for idx, item in enumerate(c_list)]
        #Scanning Up to down so 1s become the number row they are in
        u_list_up_down = [100 if item==0 else item*(c_index+1) for idx, item in enumerate(c_list)]
        #Scanning Down to Up so 1s become the number row they are in
        u_list_DU = [100 if item==0 else item*(9-c_index+1) for idx, item in enumerate(c_list)]
        #Diagonal scanning-from-upper-left 1s become column number + row number
        u_list_SUL = [100 if item==0 else item*(idx+1)+item*(c_index+1) for idx, item in enumerate(c_list)]
        u_list_SLL = [100 if item==0 else item*(9-idx+1)+item*(9-c_index+1) for idx, item in enumerate(c_list)]
        #Probing-from-upper-left 1s become max number between column and row
        u_list_PUL = [100 if item==0 else max(item*(idx+1),item*(c_index+1)) for idx, item in enumerate(c_list)]
        #Probing-from-upper-left 1s become max number between column and row from the bottom right corner
        u_list_PLR = [100 if item==0 else max(10-item*(idx+1),10-item*(c_index+1))\
        for idx, item in enumerate(c_list)]
        u_list_CEN = [100 if item==0 else max(max(9-idx-5+1,9-c_index-5+1),max(idx-5+1,c_index-5+1))\
        for idx, item in enumerate(c_list)]

        #Append each row to its chunk for techniques 
        chunks_left_right.append(u_list_left_right)
        chunks_up_down.append(u_list_up_down)
        chunks_SUL.append(u_list_SUL)
        chunks_PUL.append(u_list_PUL)
        chunks_PLR.append(u_list_PLR)
        chunks_RL.append(u_list_RL)
        chunks_DU.append(u_list_DU)
        chunks_CEN.append(u_list_CEN)
        chunks_SLL.append(u_list_SLL)
        #print(chunks_2)
    #print(chunks_left_right)

    #Turn technique chunks into Dataframes
    df_l_R = pd.DataFrame(chunks_left_right, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_u_d = pd.DataFrame(chunks_up_down, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

    df_SUL = pd.DataFrame(chunks_SUL, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_PUL = pd.DataFrame(chunks_PUL, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_PLR = pd.DataFrame(chunks_PLR, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_RL = pd.DataFrame(chunks_RL, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_DU = pd.DataFrame(chunks_DU, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_CEN = pd.DataFrame(chunks_CEN, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_SLL = pd.DataFrame(chunks_SLL, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


    #Append dataframes to lists for each letter
    df_list_up_down.append(df_u_d)
    df_list_left_right.append(df_l_R)
    df_list_SUL.append(df_SUL)
    df_list_PUL.append(df_PUL)
    df_list_PLR.append(df_PLR)
    df_list_RL.append(df_RL)
    df_list_DU.append(df_DU)
    df_list_CEN.append(df_CEN)
    df_list_SLL.append(df_SLL)

In [ ]:
print(df_list_PUL[0])

In [6]:
dgm_list = []

for index, data_frame in enumerate(df_list_up_down):
    print(index)
    dgm_up_down = lower_star_img(data_frame.to_numpy())
    print(dgm_up_down)

    dgm_left_right = lower_star_img(df_list_left_right[index].to_numpy())
    print(dgm_left_right)

    dgm_SUL = lower_star_img(df_list_SUL[index].to_numpy())
    print(dgm_SUL)

    dgm_PUL = lower_star_img(df_list_PUL[index].to_numpy())
    print(dgm_PUL)

    dgm_PLR = lower_star_img(df_list_PLR[index].to_numpy())
    print(dgm_PLR)

    dgm_RL = lower_star_img(df_list_RL[index].to_numpy())
    print(dgm_RL)
    dgm_DU = lower_star_img(df_list_DU[index].to_numpy())
    print(dgm_DU)
    dgm_CEN = lower_star_img(df_list_CEN[index].to_numpy())
    print(dgm_CEN)
    dgm_SLL = lower_star_img(df_list_SLL[index].to_numpy())
    print(dgm_SLL)
    dgm_list.append([dgm_up_down, dgm_left_right, dgm_SUL, dgm_PUL, dgm_PLR, dgm_RL, dgm_DU, dgm_CEN, dgm_SLL])

0
[[ 1. inf]]
[[ 2. inf]]
[[ 6. inf]]
[[ 4. inf]]
[[ 2. inf]]
[[ 2. inf]]
[[ 2.  5.]
 [ 2. inf]]
[[ 1. inf]]
[[11. 12.]
 [ 5. inf]]
1
[[ 1. inf]]
[[ 3. inf]]
[[ 4. inf]]
[[ 3. inf]]
[[ 2. inf]]
[[ 3.  4.]
 [ 2. inf]]
[[ 2. inf]]
[[ 1. inf]]
[[ 6. inf]]
2
[[ 2. inf]]
[[ 2. inf]]
[[ 6. inf]]
[[ 3. inf]]
[[ 2. inf]]
[[ 2.  7.]
 [ 2. inf]]
[[ 2. inf]]
[[ 2. inf]]
[[12. 15.]
 [ 6. inf]]
3
[[ 2. inf]]
[[ 3. inf]]
[[ 5. inf]]
[[ 3. inf]]
[[ 2. inf]]
[[ 1. inf]]
[[ 2. inf]]
[[ 3.  4.]
 [ 3. inf]]
[[ 6. inf]]
4
[[ 2. inf]]
[[ 3. inf]]
[[ 5. inf]]
[[ 3. inf]]
[[ 5.  7.]
 [ 2. inf]]
[[ 2.  7.]
 [ 2.  7.]
 [ 2. inf]]
[[ 2. inf]]
[[ 1. inf]]
[[ 9. 13.]
 [12. 16.]
 [ 5. inf]]
5
[[ 2. inf]]
[[ 3. inf]]
[[ 5. inf]]
[[ 3. inf]]
[[ 5. inf]]
[[ 3.  7.]
 [ 3. inf]]
[[ 2. inf]]
[[ 1. inf]]
[[10. 13.]
 [13. 16.]
 [10. inf]]
6
[[ 2. inf]]
[[ 2. inf]]
[[ 5. inf]]
[[ 3. inf]]
[[ 3. inf]]
[[ 3.  7.]
 [ 3. inf]]
[[ 3. inf]]
[[ 1. inf]]
[[13. 16.]
 [ 7. inf]]
7
[[ 2.  4.]
 [ 2. inf]]
[[ 3. inf]]
[[ 9. 10.]
 [ 5. 

In [5]:
for index, element in enumerate(dgm_list):
    for index_2, element_2 in enumerate(dgm_list):
        #print(element)
        #print(element_2)
        if np.array_equal(element, element_2) and index != index_2:
            print(index, element, index_2, element_2)

NameError: name 'dgm_list' is not defined

In [ ]:
dgm_list

In [ ]:
new_dgm = []
dgm_list_copy = copy.deepcopy(dgm_list)
for matrix in dgm_list_copy:
    temp = []
    for i in matrix:
        i[np.isinf(i)] = 100
        temp.append(i)
    new_dgm.append(temp)

In [ ]:
dist = distance_matrix(new_dgm[0][1], new_dgm[0][6])
dist

In [ ]:
sum_list = []
multi_list = []
dgm_list_copy = copy.deepcopy(dgm_list)
for matrix in dgm_list_copy:
    new_sum = 0
    new_multi = 1
    for i in matrix:
        i[np.isinf(i)] = 100
        #print(i, i.sum())
        new_sum += i.sum()
        new_multi += i.mean()
    sum_list.append(new_sum*100)
    multi_list.append(new_multi*100)

In [ ]:
#To add sum of the distance of each bar
letter_vectors = []

dgm_list_copy = copy.deepcopy(dgm_list)
for index, letter in enumerate(dgm_list_copy):
    lengths = []
    new_sum = 0
    distances = []
    #print(len(letter))
    for index_2, matrix in enumerate(letter):
        lengths.append(len(matrix))
        #lengths.append(matrix.min())
        lengths.append(matrix.min())
        matrix[np.isinf(matrix)] = 0
        lengths.append(matrix.max())
        new_sum += matrix.sum()
        for i in range(0, 6-index_2):
            #print(index_2, i+1+index_2)
            spatial_distance = distance_matrix(new_dgm[index][index_2], new_dgm[index][i+1+index_2])
            distances.append(spatial_distance.sum())
    dist_sum = 0
    #print(np.array(distances).var())
    for index_3, dist in enumerate(distances):
        dist_sum += dist.sum()
    lengths.append(new_sum/10)
    lengths.append(dist_sum/100)
    #lengths.append(np.array(distances).cov())
    letter_vectors.append(lengths)
    if index in [11, 15, 2, 6]:
        print(lengths)

In [ ]:
len(letter_vectors[0])

In [ ]:
max_dist=-1
v1=0
v2=0
for i in range(len(letter_vectors)):
    for j in range(len(letter_vectors)):
        a=np.array(letter_vectors[i])
        b=np.array(letter_vectors[j])
        dist=np.linalg.norm(a-b)
        #print('distance', dist,'between letters',i,j)
        if dist > max_dist:
            max_dist=dist
            v1=i
            v2=j
            print('found larger distance:',max_dist,'letters:',v1,v2)
print('max distance:', max_dist, 'letters',v1,v2)

In [ ]:
min_dist=10000000
v1=0
v2=0
for i in range(len(letter_vectors)):
    for j in range(len(letter_vectors)):
        if not i==j:
            a=np.array(letter_vectors[i])
            b=np.array(letter_vectors[j])
            dist=np.linalg.norm(a-b)
            #print('distance', dist,'between letters',alphabet_full[i],alphabet_full[j])
            if dist < min_dist:
                min_dist=dist
                v1=i
                v2=j
                print('found smaller distance:',min_dist,'letters:',alphabet_full[i],alphabet_full[j])
print('min distance:', min_dist, 'letters',alphabet_full[i],alphabet_full[j])

In [ ]:
#test
'''
Todo:
Get this down to only one loop
Fix rerun
'''

#list of each Scanning technique, empty lists
# for index_df in enumerate(data_chunk):
#      
#     data_chunk= [df_l_R,df_u_d,df_SUL,df_PUL,df_PLR]
    
df_list_up_down_test, df_list_left_right_test, df_list_SUL_test, df_list_PUL_test, df_list_PLR_test,\
df_list_RL_test, df_list_DU_test, df_list_CEN_test, df_list_SLL_test = ([] for i in range(9))

#iiterate through each row that represents part of the Latin Alphabet
for index, row in enumerate([single_list]):
    #Chunks turns the row of 100 to 10 lists of 10 elments
    chunks = [list(row)[x:x+10] for x in range(0, len(list(row)), 10)]
    #print(chunks)
    #Creates empty list for each scanning technique to append the chunks
    chunks_up_down_test, chunks_left_right_test, chunks_SUL_test, chunks_PUL_test, chunks_PLR_test,\
    chunks_RL_test, chunks_DU_test, chunks_CEN_test, chunks_SLL_test = ([] for i in range(9))

    #loop through cunck of 1s and 0s I think could be turned into list comprehension
    for c_index, c_list in enumerate(chunks):
        #Creates empty list for each row
        u_list_up_down_test, u_list_left_right_test, u_list_SUL_test, u_list_PUL_test, u_list_PLR_test,\
        u_list_RL_test, u_list_DU_test, u_list_CEN_test, u_list_SLL_test = ([] for i in range(9))

        #List comprehension for creating the scanned numbers in each row
        #Scanning left to right 1s become the number column they are in
        u_list_left_right_test = [100 if item==0 else item*(idx+1) for idx, item in enumerate(c_list)]
        #Scanning Right to Left
        u_list_RL_test = [100 if item==0 else 10-item*(idx+1) for idx, item in enumerate(c_list)]
        #Scanning Up to down so 1s become the number row they are in
        u_list_up_down_test = [100 if item==0 else item*(c_index+1) for idx, item in enumerate(c_list)]
        #Scanning Down to Up so 1s become the number row they are in
        u_list_DU_test = [100 if item==0 else item*(9-c_index+1) for idx, item in enumerate(c_list)]
        #Diagonal scanning-from-upper-left 1s become column number + row number
        u_list_SUL_test = [100 if item==0 else item*(idx+1)+item*(c_index+1) for idx, item in enumerate(c_list)]
        u_list_SLL_test = [100 if item==0 else item*(9-idx+1)+item*(9-c_index+1) for idx, item in enumerate(c_list)]
        #Probing-from-upper-left 1s become max number between column and row
        u_list_PUL_test = [100 if item==0 else max(item*(idx+1),item*(c_index+1)) for idx, item in enumerate(c_list)]
        #Probing-from-upper-left 1s become max number between column and row from the bottom right corner
        u_list_PLR_test = [100 if item==0 else max(10-item*(idx+1),10-item*(c_index+1))\
        for idx, item in enumerate(c_list)]
        u_list_CEN_test = [100 if item==0 else max(max(9-idx-5+1,9-c_index-5+1),max(idx-5+1,c_index-5+1))\
        for idx, item in enumerate(c_list)]

        #Append each row to its chunk for techniques 
        chunks_left_right_test.append(u_list_left_right_test)
        chunks_up_down_test.append(u_list_up_down_test)
        chunks_SUL_test.append(u_list_SUL_test)
        chunks_PUL_test.append(u_list_PUL_test)
        chunks_PLR_test.append(u_list_PLR_test)
        chunks_RL_test.append(u_list_RL_test)
        chunks_DU_test.append(u_list_DU_test)
        chunks_CEN_test.append(u_list_CEN_test)
        chunks_SLL_test.append(u_list_SLL_test)
        #print(chunks_2)
    #print(chunks_left_right)

    #Turn technique chunks into Dataframes
    df_l_R_test = pd.DataFrame(chunks_left_right_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_u_d_test = pd.DataFrame(chunks_up_down_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

    df_SUL_test = pd.DataFrame(chunks_SUL_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_PUL_test = pd.DataFrame(chunks_PUL_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_PLR_test = pd.DataFrame(chunks_PLR_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_RL_test = pd.DataFrame(chunks_RL_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_DU_test = pd.DataFrame(chunks_DU_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_CEN_test = pd.DataFrame(chunks_CEN_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    df_SLL_test = pd.DataFrame(chunks_SLL_test, columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                    index=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


    #Append dataframes to lists for each letter
    df_list_up_down_test.append(df_u_d_test)
    df_list_left_right_test.append(df_l_R_test)
    df_list_SUL_test.append(df_SUL_test)
    df_list_PUL_test.append(df_PUL_test)
    df_list_PLR_test.append(df_PLR_test)
    df_list_RL_test.append(df_RL_test)
    df_list_DU_test.append(df_DU_test)
    df_list_CEN_test.append(df_CEN_test)
    df_list_SLL_test.append(df_SLL_test)

In [ ]:
print(df_list_left_right_test[0])

In [ ]:
dgm_list_test = []

for index, data_frame in enumerate(df_list_up_down_test):
    print(index)
    dgm_up_down = lower_star_img(data_frame.to_numpy())
    print(dgm_up_down)

    dgm_left_right = lower_star_img(df_list_left_right_test[index].to_numpy())
    print(dgm_left_right)

    dgm_SUL = lower_star_img(df_list_SUL_test[index].to_numpy())
    print(dgm_SUL)

    dgm_PUL = lower_star_img(df_list_PUL_test[index].to_numpy())
    print(dgm_PUL)

    dgm_PLR = lower_star_img(df_list_PLR_test[index].to_numpy())
    print(dgm_PLR)

    dgm_RL = lower_star_img(df_list_RL_test[index].to_numpy())
    print(dgm_RL)
    dgm_DU = lower_star_img(df_list_DU_test[index].to_numpy())
    print(dgm_DU)
    dgm_CEN = lower_star_img(df_list_CEN_test[index].to_numpy())
    print(dgm_CEN)
    dgm_SLL = lower_star_img(df_list_SLL_test[index].to_numpy())
    print(dgm_SLL)
    dgm_list_test.append([dgm_up_down, dgm_left_right, dgm_SUL, dgm_PUL, dgm_PLR, dgm_RL, dgm_DU, dgm_CEN, dgm_SLL])

In [ ]:
#To add sum of the distance of each bar
letter_vectors_test = []

dgm_list_test_copy = copy.deepcopy(dgm_list_test)
for index, letter in enumerate(dgm_list_test_copy):
    lengths = []
    new_sum = 0
    distances = []
    #print(len(letter))
    for index_2, matrix in enumerate(letter):
        lengths.append(len(matrix))
        #lengths.append(matrix.min())
        lengths.append(matrix.min())
        matrix[np.isinf(matrix)] = 0
        lengths.append(matrix.max())
        new_sum += matrix.sum()
        for i in range(0, 6-index_2):
            #print(index_2, i+1+index_2)
            spatial_distance = distance_matrix(new_dgm[index][index_2], new_dgm[index][i+1+index_2])
            distances.append(spatial_distance.sum())
    dist_sum = 0
    #print(np.array(distances).var())
    for index_3, dist in enumerate(distances):
        dist_sum += dist.sum()
    lengths.append(new_sum/10)
    lengths.append(dist_sum/100)
    #lengths.append(np.array(distances).cov())
    letter_vectors_test.append(lengths)

In [ ]:
letter_vectors_test[0]

min_dist=10000000
v1=0
v2=0
for i in range(len(letter_vectors_test)):
    for j in range(len(letter_vectors)):
        if not i==j:
            a=np.array(letter_vectors[i])
            b=np.array(letter_vectors[j])
            dist=np.linalg.norm(a-b)
            print('distance', dist,'between letters',i,j)
            if dist < min_dist:
                min_dist=dist
                v1=i
                v2=j
                print('found smaller distance:',min_dist,'letters:',v1,v2)
print('min distance:', min_dist, 'letters',v1,v2)

In [ ]:
letters=np.genfromtxt('letters.csv', dtype=int, delimiter=',')

In [ ]:
letters

In [ ]:
dgmLR = [None]*26
for i in range(26):    
    letter_one_line=letters[i,:]
    # initialize matrix of size 10x10 with all values 100    
    letter=np.full((10, 10), 100)
    # convert one line letter to 10x10 matrix replacing zeros with 100
    for k in range(1,101):
        if letter_one_line[k]==1.0:            
            row=int((k-1)/10)             
            column=(k-1)%10            
            letter[row,column]=k%10    
    dgmLR[i] = lower_star_img(letter)

In [ ]:
#diagnal scanning
#diagonal scanning-from-upper-left
#Column+row-1
dgmSUL = [None]*26
for i in range(26):    
    letter_one_line=letters[i,:]
    # initialize matrix of size 10x10 with all values 100    
    letter=np.full((10, 10), 100)
    # convert one line letter to 10x10 matrix replacing zeros with 100
    for k in range(1,101):
        if letter_one_line[k]==1.0:            
            row=int((k-1)/10)             
            column=(k-1)%10            
            letter[row,column]=9-k%10 + 9-int((k-1)/10)+1
    print(letter, '\n')         
    dgmSUL[i] = lower_star_img(letter)

In [ ]:
dgmCEN = [None]*26
for i in range(26):    
    letter_one_line=letters[i,:]
    # initialize matrix of size 10x10 with all values 100    
    letter=np.full((10, 10), 100)
    # convert one line letter to 10x10 matrix replacing zeros with 100
    for k in range(1,101):
        if letter_one_line[k]==1.0:            
            row=int((k-1)/10)             
            column=(k-1)%10            
            letter[row,column]=max(max(9-row-5+1,9-column-5+1),max(row-5+1,column-5+1))
    print(letter, '\n')
    dgmSUL[i] = lower_star_img(letter)

In [ ]:
letter

In [ ]:
#probing-from-upper-left
dgmPUL = [None]*26
for i in range(26):
    letter_one_line=letters[i,:]
    # initialize matrix of size 10x10 with all values 100    
    letter=np.full((10, 10), 100)
    # convert one line letter to 10x10 matrix replacing zeros with 100
    for k in range(1,101):
        if letter_one_line[k]==1.0:            
            row=int((k-1)/10)             
            column=(k-1)%10            
            letter[row,column]=max((k-1)%10,int((k-1)/10))             
    dgmPUL[i] = lower_star_img(letter)

In [ ]:
letter

In [ ]:
print(df_list_up_down[25])

In [ ]:
#probing-from-lower-right
dgmPLR = [None]*32
for i in range(32):    
    letter_one_line=letters[i,:]
    # initialize matrix of size 10x10 with all values 100    
    letter=np.full((10, 10), 100)
    # convert one line letter to 10x10 matrix replacing zeros with 100
    for k in range(1,101):
        if letter_one_line[k]==1.0:            
            row=int((k-1)/10)             
            column=(k-1)%10            
            letter[row,column]=max(9-(k-1)%10,9-int((k-1)/10))
    print(letter, '/n')        
    dgmPLR[i] = lower_star_img(letter)

In [ ]:
letter

In [ ]:
dgm_list = []

for index, data_frame in enumerate(df_list_up_down):
    print(index)
    dgm_up_down = lower_star_img(data_frame.to_numpy())
    plt.figure(figsize=(10, 5))
    plt.subplots_adjust(right=2.5)
    plt.subplot(151)
    plt.imshow(data_frame)
    plt.colorbar()
    plt.title(f"Letter {index}")

    dgm_up_down = lower_star_img(data_frame.to_numpy())
    plt.subplot(162)
    plt.title(f"0-D Persistence Diagram U to D {index}")
    if len(dgm_up_down) < 2:
        plot_diagrams(np.concatenate((dgm_up_down,[[0, 0]]),axis = 0))
    else:
        plot_diagrams(dgm_up_down)
    print(dgm_up_down)

    dgm_left_right = lower_star_img(df_list_left_right[index].to_numpy())
    plt.subplot(163)
    plt.title(f"0-D Persistence Diagram L to R {index}")
    if len(dgm_left_right) < 2:
        plot_diagrams(np.concatenate((dgm_left_right,[[0, 0]]),axis = 0))
    else:
        plot_diagrams(dgm_left_right)
    print(dgm_left_right)

    dgm_SUL = lower_star_img(df_list_SUL[index].to_numpy())
    plt.subplot(164)
    plt.title(f"0-D Persistence Diagram SUL {index}")
    if len(dgm_SUL) < 2:
        plot_diagrams(np.concatenate((dgm_SUL,[[0, 0]]),axis = 0))
    else:
        plot_diagrams(dgm_SUL)
    print(dgm_SUL)

    dgm_PUL = lower_star_img(df_list_PUL[index].to_numpy())
    plt.subplot(165)
    plt.title(f"0-D Persistence Diagram PUL {index}")
    if len(dgm_PUL) < 2:
        plot_diagrams(np.concatenate((dgm_PUL,[[0, 0]]),axis = 0))
    else:
        plot_diagrams(dgm_PUL)
    print(dgm_PUL)

    dgm_PLR = lower_star_img(df_list_PLR[index].to_numpy())
    plt.subplot(166)
    plt.title(f"0-D Persistence Diagram PLR {index}")
    if len(dgm_PLR) < 2:
        plot_diagrams(np.concatenate((dgm_PLR,[[0, 0]]),axis = 0))
    else:
        plot_diagrams(dgm_PLR)
    print(dgm_PLR)

    dgm_RL = lower_star_img(df_list_RL[index].to_numpy())
    dgm_DU = lower_star_img(df_list_DU[index].to_numpy())
    dgm_list.append([dgm_up_down, dgm_left_right, dgm_SUL, dgm_PUL, dgm_PLR, dgm_RL, dgm_DU])
    plt.show()

In [ ]:
#Legacy
'''
for idx, item in enumerate(c_list):
    if item==0:
        u_list_up_down.append(100)
        u_list_left_right.append(100)
        u_list_SUL.append(100)
        u_list_PUL.append(100)
        u_list_PLR.append(100)
    else:
        u_list_left_right.append(item*(idx+1))
        u_list_up_down.append(item*(c_index+1))
        u_list_SUL.append(item*(idx+1)+item*(c_index+1))
        u_list_PUL.append(max(item*(idx+1),item*(c_index+1)))
        u_list_PLR.append(max(10-item*(idx+1),10-item*(c_index+1)))
'''

In [ ]:
#testing
lines = 2*10
#ten lists
#3rd line 3rd element of the 1st list, 2nd element of the 2nd list and 1st element 3rd list
test_lists = train['NTQ'][2].to_numpy()
print(test_lists)
distance = []
for i in range(1,lines):
    distance.append(min(i, lines-i))
print(distance)

#Left to Right diagonal
diagonal_list = []
for idx, i in enumerate(distance):
    print('Distance: ', i)
    temp_list = []
    print('Line: ', idx)
    for index, elem in enumerate(range(1, i+1)):
        #print(elem, i)
        if idx > 9:
            #(2,10) or (10,2)
            print(10-i,10-elem)
            temp_list.append(test_lists[10-i][10-elem])
        else:
            print(elem-1, i-1)
            temp_list.append(test_lists[elem-1][i-1])
        i = i-1
    diagonal_list.append(temp_list)
#print(diagonal_list)
for diag_list in diagonal_list:
    vertices = diag_list.count(1)
    last_element = 0
    edges = 0
    for i in diag_list:
        if i == 1 and last_element == 0:
            edges += 1
        last_element = i
    if vertices == 0:
        zero_diag_homology = 0
    else:
        zero_diag_homology = round(edges/vertices,4)
    #print(zero_diag_homology)

#Right to left diagonal
diagonal_list = []
for idx, i in enumerate(distance):
    #print('Distance: ', i)
    temp_list = []
    #print('Line: ', idx)
    for index, elem in enumerate(range(1, i+1)):
        #print(elem, i)
        if idx > 9:
            #print(10-i,elem-1)
            temp_list.append(test_lists[10-i][elem-1])
        else:
            #print(elem-1, 10-i)
            temp_list.append(test_lists[elem-1][10-i])
        i = i-1
    diagonal_list.append(temp_list)
print(diagonal_list)
for diag_list in diagonal_list:
    vertices = diag_list.count(1)
    last_element = 0
    edges = 0
    for i in diag_list:
        if i == 1 and last_element == 0:
            edges += 1
        last_element = i
    if vertices == 0:
        zero_diag_homology = 0
    else:
        zero_diag_homology = round(edges/vertices,4)
    print(zero_diag_homology)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=c3975852-3619-4f95-970c-90c02f1f882d' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>